GET http://localhost:3000/categories

###

POST http://localhost:3000/categories
content-type: application/json

{
      "name": "Animals"
}

###

DELETE http://localhost:3000/categories/4

###

PUT http://localhost:3000/categories/3
content-type: application/json

{
      "name": "Electronics"
}

